// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/events/v1/events.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderCreated 订单创建事件
type OrderCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Total         float64                `protobuf:"fixed64,4,opt,name=total,proto3" json:"total,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreated) Reset() {
	*x = OrderCreated{}
	mi := &file_api_proto_events_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreated) ProtoMessage() {}

func (x *OrderCreated) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreated.ProtoReflect.Descriptor instead.
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreated) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCreated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderCreated) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderCreated) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderCreated) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_api_proto_events_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// InventoryReserved 库存预留成功
type InventoryReserved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReserved) Reset() {
	*x = InventoryReserved{}
	mi := &file_api_proto_events_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReserved) ProtoMessage() {}

func (x *InventoryReserved) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReserved.ProtoReflect.Descriptor instead.
func (*InventoryReserved) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryReserved) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// InventoryInsufficient 库存不足
type InventoryInsufficient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Required      int32                  `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Available     int32                  `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryInsufficient) Reset() {
	*x = InventoryInsufficient{}
	mi := &file_api_proto_events_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryInsufficient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryInsufficient) ProtoMessage() {}

func (x *InventoryInsufficient) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryInsufficient.ProtoReflect.Descriptor instead.
func (*InventoryInsufficient) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *InventoryInsufficient) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *InventoryInsufficient) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InventoryInsufficient) GetRequired() int32 {
	if x != nil {
		return x.Required
	}
	return 0
}

func (x *InventoryInsufficient) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

// PaymentRequested 请求支付
type PaymentRequested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequested) Reset() {
	*x = PaymentRequested{}
	mi := &file_api_proto_events_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequested) ProtoMessage() {}

func (x *PaymentRequested) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequested.ProtoReflect.Descriptor instead.
func (*PaymentRequested) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentRequested) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentRequested) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentRequested) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// PaymentCompleted 支付完成
type PaymentCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCompleted) Reset() {
	*x = PaymentCompleted{}
	mi := &file_api_proto_events_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCompleted) ProtoMessage() {}

func (x *PaymentCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCompleted.ProtoReflect.Descriptor instead.
func (*PaymentCompleted) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentCompleted) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentCompleted) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

// PaymentFailed 支付失败
type PaymentFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentFailed) Reset() {
	*x = PaymentFailed{}
	mi := &file_api_proto_events_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentFailed) ProtoMessage() {}

func (x *PaymentFailed) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentFailed.ProtoReflect.Descriptor instead.
func (*PaymentFailed) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentFailed) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// OrderConfirmed 订单确认
type OrderConfirmed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderConfirmed) Reset() {
	*x = OrderConfirmed{}
	mi := &file_api_proto_events_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderConfirmed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderConfirmed) ProtoMessage() {}

func (x *OrderConfirmed) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderConfirmed.ProtoReflect.Descriptor instead.
func (*OrderConfirmed) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *OrderConfirmed) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderConfirmed) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

// OrderCancelled 订单取消（补偿）
type OrderCancelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelled) Reset() {
	*x = OrderCancelled{}
	mi := &file_api_proto_events_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelled) ProtoMessage() {}

func (x *OrderCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelled.ProtoReflect.Descriptor instead.
func (*OrderCancelled) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *OrderCancelled) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCancelled) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// InventoryRelease 恢复库存（补偿）
type InventoryRelease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryRelease) Reset() {
	*x = InventoryRelease{}
	mi := &file_api_proto_events_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryRelease) ProtoMessage() {}

func (x *InventoryRelease) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryRelease.ProtoReflect.Descriptor instead.
func (*InventoryRelease) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *InventoryRelease) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *InventoryRelease) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// NotificationSent 通知已发送
type NotificationSent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationSent) Reset() {
	*x = NotificationSent{}
	mi := &file_api_proto_events_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationSent) ProtoMessage() {}

func (x *NotificationSent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationSent.ProtoReflect.Descriptor instead.
func (*NotificationSent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *NotificationSent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *NotificationSent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationSent) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *NotificationSent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_api_proto_events_v1_events_proto protoreflect.FileDescriptor

const file_api_proto_events_v1_events_proto_rawDesc = "" +
	"\n" +
	" api/proto/events/v1/events.proto\x12\tevents.v1\"\xa3\x01\n" +
	"\fOrderCreated\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12*\n" +
	"\x05items\x18\x03 \x03(\v2\x14.events.v1.OrderItemR\x05items\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x01R\x05total\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"\\\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\".\n" +
	"\x11InventoryReserved\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x8b\x01\n" +
	"\x15InventoryInsufficient\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\x05R\brequired\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\x05R\tavailable\"^\n" +
	"\x10PaymentRequested\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"L\n" +
	"\x10PaymentCompleted\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\"B\n" +
	"\rPaymentFailed\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"J\n" +
	"\x0eOrderConfirmed\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\"C\n" +
	"\x0eOrderCancelled\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"Y\n" +
	"\x10InventoryRelease\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12*\n" +
	"\x05items\x18\x02 \x03(\v2\x14.events.v1.OrderItemR\x05items\"z\n" +
	"\x10NotificationSent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontentB(Z&ecommerce/api/proto/events/v1;eventsv1b\x06proto3"

var (
	file_api_proto_events_v1_events_proto_rawDescOnce sync.Once
	file_api_proto_events_v1_events_proto_rawDescData []byte
)

func file_api_proto_events_v1_events_proto_rawDescGZIP() []byte {
	file_api_proto_events_v1_events_proto_rawDescOnce.Do(func() {
		file_api_proto_events_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_events_v1_events_proto_rawDesc), len(file_api_proto_events_v1_events_proto_rawDesc)))
	})
	return file_api_proto_events_v1_events_proto_rawDescData
}

var file_api_proto_events_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_events_v1_events_proto_goTypes = []any{
	(*OrderCreated)(nil),          // 0: events.v1.OrderCreated
	(*OrderItem)(nil),             // 1: events.v1.OrderItem
	(*InventoryReserved)(nil),     // 2: events.v1.InventoryReserved
	(*InventoryInsufficient)(nil), // 3: events.v1.InventoryInsufficient
	(*PaymentRequested)(nil),      // 4: events.v1.PaymentRequested
	(*PaymentCompleted)(nil),      // 5: events.v1.PaymentCompleted
	(*PaymentFailed)(nil),         // 6: events.v1.PaymentFailed
	(*OrderConfirmed)(nil),        // 7: events.v1.OrderConfirmed
	(*OrderCancelled)(nil),        // 8: events.v1.OrderCancelled
	(*InventoryRelease)(nil),      // 9: events.v1.InventoryRelease
	(*NotificationSent)(nil),      // 10: events.v1.NotificationSent
}
var file_api_proto_events_v1_events_proto_depIdxs = []int32{
	1, // 0: events.v1.OrderCreated.items:type_name -> events.v1.OrderItem
	1, // 1: events.v1.InventoryRelease.items:type_name -> events.v1.OrderItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_events_v1_events_proto_init() }
func file_api_proto_events_v1_events_proto_init() {
	if File_api_proto_events_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_events_v1_events_proto_rawDesc), len(file_api_proto_events_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_events_v1_events_proto_goTypes,
		DependencyIndexes: file_api_proto_events_v1_events_proto_depIdxs,
		MessageInfos:      file_api_proto_events_v1_events_proto_msgTypes,
	}.Build()
	File_api_proto_events_v1_events_proto = out.File
	file_api_proto_events_v1_events_proto_goTypes = nil
	file_api_proto_events_v1_events_proto_depIdxs = nil
}
