.PHONY: run clean

run-01:
	go run ./01-workflow-basics/main.go

run-02:
	go run ./02-activity-patterns/main.go

run-03:
	go run ./03-error-handling/main.go

run-04:
	go run ./04-signals-queries/main.go

clean:
	go clean ./...