import { generateSidebar } from 'vitepress-sidebar'

export default generateSidebar([
  {
    documentRootPath: '/part01-basics',
    scanStartPath: '',
    resolvePath: '/part01-basics/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/part02-core',
    scanStartPath: '',
    resolvePath: '/part02-core/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/part03-concurrency',
    scanStartPath: '',
    resolvePath: '/part03-concurrency/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/part04-stdlib',
    scanStartPath: '',
    resolvePath: '/part04-stdlib/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/part05-web',
    scanStartPath: '',
    resolvePath: '/part05-web/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/part06-engineering',
    scanStartPath: '',
    resolvePath: '/part06-engineering/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/part07-advanced',
    scanStartPath: '',
    resolvePath: '/part07-advanced/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/part08-projects',
    scanStartPath: '',
    resolvePath: '/part08-projects/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/part09-cloud-native',
    scanStartPath: '',
    resolvePath: '/part09-cloud-native/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/part10-performance',
    scanStartPath: '',
    resolvePath: '/part10-performance/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
])
