import { generateSidebar } from 'vitepress-sidebar'

export default generateSidebar([
  {
    documentRootPath: '/01-basics',
    scanStartPath: '',
    resolvePath: '/01-basics/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/02-core',
    scanStartPath: '',
    resolvePath: '/02-core/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/03-concurrency',
    scanStartPath: '',
    resolvePath: '/03-concurrency/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/04-stdlib',
    scanStartPath: '',
    resolvePath: '/04-stdlib/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/05-web',
    scanStartPath: '',
    resolvePath: '/05-web/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/06-engineering',
    scanStartPath: '',
    resolvePath: '/06-engineering/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/07-advanced',
    scanStartPath: '',
    resolvePath: '/07-advanced/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/08-projects',
    scanStartPath: '',
    resolvePath: '/08-projects/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/09-cloud-native',
    scanStartPath: '',
    resolvePath: '/09-cloud-native/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/10-performance',
    scanStartPath: '',
    resolvePath: '/10-performance/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
])
