// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/stream.proto

package streamrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_proto_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_stream_proto protoreflect.FileDescriptor

const file_proto_stream_proto_rawDesc = "" +
	"\n" +
	"\x12proto/stream.proto\x12\tstreamrpc\"#\n" +
	"\rStreamRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"(\n" +
	"\x0eStreamResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\xed\x01\n" +
	"\rStreamService\x12E\n" +
	"\fServerStream\x12\x18.streamrpc.StreamRequest\x1a\x19.streamrpc.StreamResponse0\x01\x12E\n" +
	"\fClientStream\x12\x18.streamrpc.StreamRequest\x1a\x19.streamrpc.StreamResponse(\x01\x12N\n" +
	"\x13BidirectionalStream\x12\x18.streamrpc.StreamRequest\x1a\x19.streamrpc.StreamResponse(\x010\x01B\x13Z\x11./proto;streamrpcb\x06proto3"

var (
	file_proto_stream_proto_rawDescOnce sync.Once
	file_proto_stream_proto_rawDescData []byte
)

func file_proto_stream_proto_rawDescGZIP() []byte {
	file_proto_stream_proto_rawDescOnce.Do(func() {
		file_proto_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stream_proto_rawDesc), len(file_proto_stream_proto_rawDesc)))
	})
	return file_proto_stream_proto_rawDescData
}

var file_proto_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_stream_proto_goTypes = []any{
	(*StreamRequest)(nil),  // 0: streamrpc.StreamRequest
	(*StreamResponse)(nil), // 1: streamrpc.StreamResponse
}
var file_proto_stream_proto_depIdxs = []int32{
	0, // 0: streamrpc.StreamService.ServerStream:input_type -> streamrpc.StreamRequest
	0, // 1: streamrpc.StreamService.ClientStream:input_type -> streamrpc.StreamRequest
	0, // 2: streamrpc.StreamService.BidirectionalStream:input_type -> streamrpc.StreamRequest
	1, // 3: streamrpc.StreamService.ServerStream:output_type -> streamrpc.StreamResponse
	1, // 4: streamrpc.StreamService.ClientStream:output_type -> streamrpc.StreamResponse
	1, // 5: streamrpc.StreamService.BidirectionalStream:output_type -> streamrpc.StreamResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_stream_proto_init() }
func file_proto_stream_proto_init() {
	if File_proto_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stream_proto_rawDesc), len(file_proto_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stream_proto_goTypes,
		DependencyIndexes: file_proto_stream_proto_depIdxs,
		MessageInfos:      file_proto_stream_proto_msgTypes,
	}.Build()
	File_proto_stream_proto = out.File
	file_proto_stream_proto_goTypes = nil
	file_proto_stream_proto_depIdxs = nil
}
