server:
  http:
    network: tcp
    addr: 0.0.0.0:8080
    timeout: 60

services:
  user:
    addr: localhost:8081
  product:
    addr: localhost:8082
  order:
    addr: localhost:8083
  payment:
    addr: localhost:8084

logger:
  level: info
  format: json
  output_path: logs/api-gateway.log